apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3scale-gitops-api-generic-hml
  namespace: openshift-gitops
  labels:
    3scale: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: 3scale-dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 'Generic/values/generic'
    helm:
      valueFiles:
        - 'application.yaml'
        - 'backend.yaml'
        - 'developer-account.yaml'
        - 'developer-user.yaml'
        - 'product.yaml'
        - 'activedoc.yaml'
    repoURL: 'https://github.com/adregis/gitops-3scale-api'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
